@Löwen.Api_HostAddress = https://localhost:7197


//Auth Endpoints
###
POST {{Löwen.Api_HostAddress}}/api/Auth/Register
Content-Type: application/json
{
  "email": "ae1378032@gmail5.com",
  "userName": "ali-05",
  "password": "Ali1@.com"
}
###
PUT {{Löwen.Api_HostAddress}}/api/Users/Update
Content-Type: application/json
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhbGktMDUiLCJqdGkiOiI1OTA0Yzc4Ni04OWVhLTQ1YzYtOGMyNC1jNjUyZGJmZmNmNTAiLCJlbWFpbCI6ImFlMTM3ODAzMkBnbWFpbDUuY29tIiwidW5pcXVlX25hbWUiOiJhbGktMDUiLCJuYW1laWQiOiIzZmUwOWJkNy02ZjAyLTQyZGMtOGY0Ni00NTE0YjkxMWZkM2YiLCJleHAiOjE3NTgwMjI2NzQsImlzcyI6IkxvY2FsSG9zdCIsImF1ZCI6IkxvY2FsSG9zdCJ9.E-4PQdjYeCkBFjledHx8rG_vXu31Hkq1l0EGZP42h0s"
  ,"fName": "Ali5",
  "mName": null,
  "lName": "Elsaied5",
  "dateOfBirth": "2005-09-16",
  "phoneNumber": "01096897418",
  "gender": "M"
}
###

//RootAdmin Endpoints
POST {{Löwen.Api_HostAddress}}/api/RootAdmin/add-admin
Content-Type: application/json

{
  "email": "se1378032@gmail.com",
  "userName": "ali@@@",
  "password": "Alxcvbnxcv1!",
  "fName": "Ali",
  "mName": null,
  "lName": "Elsaied",
  "DateOfBirth": "2004-09-09",
  "phoneNumber": "01096897418",
  "gender": "M"
}
###
POST {{Löwen.Api_HostAddress}}/api/RootAdmin/assign-role/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,2

###
DELETE {{Löwen.Api_HostAddress}}/api/RootAdmin/Remove-Role-From-User-admin/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,2

###
DELETE {{Löwen.Api_HostAddress}}/api/RootAdmin/remove-admin/ab62424c-e406-42bb-97d1-7479ecc3dbce

###
PUT {{Löwen.Api_HostAddress}}/api/RootAdmin/mark-admin-as-deleted/3fe09bd7-6f02-42dc-8f46-4514b911fd3f

###
PUT {{Löwen.Api_HostAddress}}/api/RootAdmin/activate-marked-as-deleted/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admin-by-id/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,1

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admin-by-email/ae1378032@gmail.com,2

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admins/3
###

//Admin Endpoints

POST {{Löwen.Api_HostAddress}}/api/Admin/add-category
Content-Type: application/json
{
  "category": "string",
  "gender": "M",
  "ageFrom": 1,
  "ageTo": 3
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-category
Content-Type: application/json
{
  "id": "1e1c18bc-b7dd-4f36-98a9-09c9e54561cd",
  "category":null,
  "gender": null,
  "ageFrom":null,
  "ageTo": 5
}

###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-category/1e2c18bc-b7dd-4f36-98a9-09c9e54561cd
###

POST {{Löwen.Api_HostAddress}}/api/Admin/add-Tag
Content-Type: application/json
{
  "Tag": "#Men #modern #Style",
  "productId": "210a36db-77b5-4f04-8be7-0c55fa95d7bc"
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-Tag/9dddf314-b433-4a15-a157-e4d11a7a5de5,"#dd"


###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-Tag/9dddf314-b433-4a15-a157-e4d11a7a5de5
###

POST {{Löwen.Api_HostAddress}}/api/Admin/add-product
Content-Type: application/json
{
  "name": "Product 1",
  "description": "Product 1",
  "price": 1423,
  "stockQuantity": 222,
  "status": 1,
  "categoryId": "512813e2-5167-4dd5-891a-6e9544500033"
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-product
Content-Type: application/json
{
  "id": "51a1018c-2029-46da-8044-6aa8f9ebc039",
  "description": null,
  "price": null,
  "stockQuantity": null,
  "status": 2,
  "categoryId": "512813e2-5167-4dd5-891a-6e9544500033"
}

###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-product/51a1018c-2029-46da-8044-6aa8f9ebc039
###

###
GET {{Löwen.Api_HostAddress}}/api/Admin/get-user-by-id/97eece48-71cb-4f31-b7be-b032cfb73779
###
GET {{Löwen.Api_HostAddress}}/api/Admin/get-user-by-email/ae1378032@gmail3.com
###
GET {{Löwen.Api_HostAddress}}/api/Admin/get-users-paged/3,2


###
PUT {{Löwen.Api_HostAddress}}/api/Admin/mark-user-as-deleted/3fe09bd7-6f02-42dc-8f46-4514b911fd3f

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/activate-marked-user-as-deleted/3fe09bd7-6f02-42dc-8f46-4514b911fd3f
