@Löwen.Api_HostAddress = https://localhost:7197

//RootAdmin Endpoints
##
POST {{Löwen.Api_HostAddress}}/api/RootAdmin/add-admin
Content-Type: application/json

{
  "email": "se1378032@gmail.com",
  "userName": "ali@@@",
  "password": "Alxcvbnxcv1!",
  "fName": "Ali",
  "mName": null,
  "lName": "Elsaied",
  "DateOfBirth": "2004-09-09",
  "phoneNumber": "01096897418",
  "gender": "M"
}

###
POST {{Löwen.Api_HostAddress}}/api/RootAdmin/assign-role/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,2

###
DELETE {{Löwen.Api_HostAddress}}/api/RootAdmin/Remove-Role-From-User-admin/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,2

###
DELETE {{Löwen.Api_HostAddress}}/api/RootAdmin/remove-admin/ab62424c-e406-42bb-97d1-7479ecc3dbce

###
PUT {{Löwen.Api_HostAddress}}/api/RootAdmin/mark-admin-as-deleted/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc

###
PUT {{Löwen.Api_HostAddress}}/api/RootAdmin/activate-marked-as-deleted/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admin-by-id/7d68f512-05e3-49c6-8cc9-5fbeed6b00fc,1

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admin-by-email/ae1378032@gmail.com,2

###
GET {{Löwen.Api_HostAddress}}/api/RootAdmin/admins/3
###

//Admin Endpoints

POST {{Löwen.Api_HostAddress}}/api/Admin/add-category
Content-Type: application/json
{
  "category": "string",
  "gender": "M",
  "ageFrom": 1,
  "ageTo": 3
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-category
Content-Type: application/json
{
  "id": "1e1c18bc-b7dd-4f36-98a9-09c9e54561cd",
  "category":null,
  "gender": null,
  "ageFrom":null,
  "ageTo": 5
}

###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-category/1e2c18bc-b7dd-4f36-98a9-09c9e54561cd
###

POST {{Löwen.Api_HostAddress}}/api/Admin/add-Tag
Content-Type: application/json
{
  "Tag": "#Men #modern #Style",
  "productId": "210a36db-77b5-4f04-8be7-0c55fa95d7bc"
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-Tag/9dddf314-b433-4a15-a157-e4d11a7a5de5,"#dd"


###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-Tag/9dddf314-b433-4a15-a157-e4d11a7a5de5
###

POST {{Löwen.Api_HostAddress}}/api/Admin/add-product
Content-Type: application/json
{
  "name": "Product 1",
  "description": "Product 1",
  "price": 1423,
  "stockQuantity": 222,
  "status": 1,
  "categoryId": "512813e2-5167-4dd5-891a-6e9544500033"
}

###
PUT {{Löwen.Api_HostAddress}}/api/Admin/update-product
Content-Type: application/josn
{
  "id": "string",
  "name": null,
  "description":null,
  "price": null,
  "stockQuantity": null,
  "status": null,
  "categoryId": null
}

###
DELETE {{Löwen.Api_HostAddress}}/api/Admin/remove-product/c658e6f8-9c8c-46ab-a259-074bc91c97dc
