@Löwen_Api_HostAddress = https://localhost:7197


//Auth Endpoints
###
POST {{Löwen_Api_HostAddress}}/api/Auth/Register
Content-Type: application/json
{
  "email": "ae1378032@gmail.com",
  "userName": "ali-01sdf",
  "password": "Ali1@.com1"
}

###
POST https://localhost:7197/api/auth/login
Content-Type: application/json

{
  "userNameOrEmail": "ali-01",
  "password": "Ali1@.com1"
}

