@Löwen.Api_HostAddress = https://localhost:7197/api/Coupon
@token = your_jwt_token_here

### Add coupon
POST {{Löwen.Api_HostAddress}}/add-coupon
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "code": "DISCOUNT35",
  "DiscountType": 1,
  "DiscountValue": 25,
  "StartDate": "2025-10-01T00:00:00Z",
  "EndDate": "2025-10-31T23:59:59Z",
  "isActive": true,
  "usageLimit" : 100
}

###

### Update coupon
PUT {{Löwen.Api_HostAddress}}/update-coupon
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "CouponId" : "1ded628d-c3eb-4f00-a4a2-64f9a3ee8820",
  "code": "DISCOUNT25",
  "DiscountType": 1,
  "DiscountValue": 244,
  "StartDate": "2025-10-01T00:00:00Z",
  "EndDate": "2025-10-31T23:59:59Z",
  "isActive": true,
  "usageLimit" : 100
}

###

### Remove coupon
DELETE {{Löwen.Api_HostAddress}}/remove-coupon/1ded628d-c3eb-4f00-a4a2-64f9a3ee8820
Authorization: Bearer {{token}}

###

### Apply coupon to order
POST {{Löwen.Api_HostAddress}}/apply-coupon-to-order/DISCOUNT25,9f5d3a2e-4b6c-8e9f-0a1b-2c3d4e5f6a7b
Authorization: Bearer {{token}}

###

### Remove coupon from order
DELETE {{Löwen.Api_HostAddress}}/remove-coupon-from-order/DISCOUNT25,9f5d3a2e-4b6c-8e9f-0a1b-2c3d4e5f6a7b
Authorization: Bearer {{token}}

###

### Get coupon by ID
GET {{Löwen.Api_HostAddress}}/get-coupon-by-id/c5ba66ab-7c16-41a6-801c-8b6669341e5b

###

### Get coupon by code
GET {{Löwen.Api_HostAddress}}/get-coupon-by-code/DISCOUNT15
Authorization: Bearer {{token}}

###

### Get all coupons (paged)
GET {{Löwen.Api_HostAddress}}/get-all-coupons-paged/1,2
Authorization: Bearer {{token}}
# For more info on HTTP files go to https://aka.ms/vs/httpfile
