@Löwen_Api_HostAddress = https://localhost:7197/api/Order
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjhmMmVmZDEwLTJkMWMtNDFlZS05YzRkLTJmN2Y1NDMxY2IxOCIsImp0aSI6Ijg4ZWJmNWYxLTM0M2QtNDA5ZC05OTM3LTNhNDQ5MjA0NDhkZCIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsMS5jb20iLCJ1bmlxdWVfbmFtZSI6ImFsaS0wMSIsInJvbGVzIjoiVXNlciIsImV4cCI6MTc1ODczNTYwMCwiaXNzIjoiTG9jYWxIb3N0IiwiYXVkIjoiTG9jYWxIb3N0In0.gnujMYTtJXMqkUKZ0o2SLIZR9hM8cN5UFk3Y1uPIYrs
//Order Endpoints

###
POST {{Löwen_Api_HostAddress}}/add-order
Authorization: Bearer {{token}}
