@Löwen_Api_HostAddress = https://localhost:7197/api/Order
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ1ZWNjNDU3LTI3ZmUtNDE3NC1hYWMxLTFlMzk3YTMzNzIyNiIsImp0aSI6ImFhYjUzZDFiLWNiM2QtNDljNS04ZTgzLTNiMjY0N2VkNzAxZCIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsMTExLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxc2RmMTExIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzYyNjA0Mzk5LCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.QH_B7IF6k2WPEHBmRDj6x-9xZ9y64qyo4g8hQKKU-lU
//Order Endpoints

###
POST {{Löwen_Api_HostAddress}}/add-order
Authorization: Bearer {{token}}
Content-Type : application/json

{
  "items": [
    {
      "productId": "3a61f106-7610-43ad-bb32-b5ec5dd92305",
      "quantity": 1,
      "priceAtPurchase":110
    },
    {
      "productId": "4135429f-ad84-40bc-a232-5cc7240e378a",
      "quantity": 1,
      "priceAtPurchase":110
    },
    {
      "productId": "fc5ae1fd-4608-4918-bc24-87a3e85eff7e",
      "quantity": 1,
      "priceAtPurchase":110
    }
  ]
}

###
PUT {{Löwen_Api_HostAddress}}/update-order-status/613e1447-ef9a-49d3-b4fc-4002b9af5b30,9
Authorization: Bearer {{token}}

###
PUT {{Löwen_Api_HostAddress}}/update-order-items
Authorization: Bearer {{token}}
Content-Type : application/json
{
  "orderId": "e3185c73-9555-40c9-a5ca-fc518cb1bce2",
  "productId": "128ebf90-5896-4e53-8a97-826c8173830a",
  "quantity": 0,
  "priceAtPurchase": 0
}
###
GET {{Löwen_Api_HostAddress}}/get-order-details/392ee13a-7ccb-48ad-82b0-f0cba29b7b72

###
GET {{Löwen_Api_HostAddress}}/get-orders-by-user-paged/1,3
Authorization : Bearer {{token}}

###
GET {{Löwen_Api_HostAddress}}/get-orders-paged/1,1
Authorization : Bearer {{token}}