@Löwen.Api_HostAddress = https://localhost:7197/api/users


GET {{Löwen.Api_HostAddress}}/get-user-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6IjhiMjhhNzc2LTJjMWEtNDliYS1iZmVmLTYwZTc1YjA4MGM3YSIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MTEwMDgwLCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.B3Mmm0w7WyS_TsgOEhVyfFH8PV4_Jvn6OfsXE1vtNHI
###
PUT {{Löwen.Api_HostAddress}}/update-user-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImJjZGQ1ZWRiLThhNWMtNDI5MS04YTViLTI1MjcwZTlmMDJjYSIsImp0aSI6Ijg1MmY3OTk0LTA0YmUtNDllNS1iZjYwLTZiNGNjMzI5NzFmNyIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsMi5jb20iLCJ1bmlxdWVfbmFtZSI6ImFsaS0wMiIsInJvbGVzIjoiVXNlciIsImV4cCI6MTc1ODEwOTU2NCwiaXNzIjoiTG9jYWxIb3N0IiwiYXVkIjoiTG9jYWxIb3N0In0.L_wErDRk4uaGFlsWLksVcWdDWmh-WrSCNlkqWqTniBw
Content-Type: application/json
{
  "fName": "Ali5",
  "mName": null,
  "lName": "Elsaied5",
  "dateOfBirth": "2005-09-16",
  "phoneNumber": "01096897418",
  "gender": "M"
}
###
PUT {{Löwen.Api_HostAddress}}/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6IjhiMjhhNzc2LTJjMWEtNDliYS1iZmVmLTYwZTc1YjA4MGM3YSIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MTEwMDgwLCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.B3Mmm0w7WyS_TsgOEhVyfFH8PV4_Jvn6OfsXE1vtNHI
Content-Type: application/json
{
  "currentPassword": "Ali1@.com",
  "password": "Ali1@.com1",
  "confermPassword": "Ali1@.com1"
}