@Löwen.Api_HostAddress = https://localhost:7197/api/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImVkNDExZmM5LTdlZGMtNDM4Yy04MmRkLTcwZWM3OTAwMDY4MSIsImp0aSI6ImYwNmU4NGJlLWVhNWYtNGJmZi1hZjRjLTlkNmFiODRkMDU1MCIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxc2RmIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzYxMzMzNTI1LCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.bY0pdayTe7ZoQljrB8vjfHYmVlkzGK0KP61A3ntfQgs

GET {{Löwen.Api_HostAddress}}/get-user-info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6IjhiMjhhNzc2LTJjMWEtNDliYS1iZmVmLTYwZTc1YjA4MGM3YSIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MTEwMDgwLCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.B3Mmm0w7WyS_TsgOEhVyfFH8PV4_Jvn6OfsXE1vtNHI
###
PUT {{Löwen.Api_HostAddress}}/update-user-info
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "fName": "Ali5",
  "mName": null,
  "lName": "Elsaied5",
  "dateOfBirth": "2005-09-16",
  "phoneNumber": "01096897418",
  "addressDetails": "14-4",
  "gender": "M"
}
###
PUT {{Löwen.Api_HostAddress}}/change-password
Authorization: Bearer 
Content-Type: application/json
{
  "currentPassword": "Ali1@.com",
  "password": "Ali1@.com1",
  "confermPassword": "Ali1@.com1"
}

###
PUT https://localhost:7197/api/users/update-profile-image
Authorization: Bearer {{token}}
accept: */*
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="Image"; filename="Digitel view.jpg"
Content-Type: image/jpg

< G:\photos\Digitel view.jpg
--WebAppBoundary--


###
POST {{Löwen.Api_HostAddress}}/verify-own-email/ae1378032@gmail.com
###
POST {{Löwen.Api_HostAddress}}/add-product-to-wishlist/206ee09a-140f-4ae4-b319-7dc3b8de3e15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6IjY0OGVhYWYyLTJkMGUtNDViMS04OGM5LTQ4Njc4YjgzMGRlNCIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MjA3MDQ0LCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.4ot2kzKglVmPjw5XmBOtG11kG7j_-P5JHDupq1ruq9Q

###
DELETE {{Löwen.Api_HostAddress}}/remove-product-from-wishlist/206ee09a-140f-4ae4-b319-7dc3b8de3e15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6IjY0OGVhYWYyLTJkMGUtNDViMS04OGM5LTQ4Njc4YjgzMGRlNCIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MjA3MDQ0LCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.4ot2kzKglVmPjw5XmBOtG11kG7j_-P5JHDupq1ruq9Q
###
POST {{Löwen.Api_HostAddress}}/add-love-for-product/377e8919-3f4d-49da-bbd8-8c51ca37f527
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6ImExMWUzZTkwLTA3NmQtNGRjMi05MjhlLTUzMTNhOGU2YWMxNyIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MjI5MTIwLCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.lKRRDfjGmEnLG-cKxCc4lUUIguBFghE57wS-bYwWp7E

###
DELETE {{Löwen.Api_HostAddress}}/remove-love-from-product/377e8919-3f4d-49da-bbd8-8c51ca37f527
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijk3ZWVjZTQ4LTcxY2ItNGYzMS1iN2JlLWIwMzJjZmI3Mzc3OSIsImp0aSI6ImExMWUzZTkwLTA3NmQtNGRjMi05MjhlLTUzMTNhOGU2YWMxNyIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsLmNvbSIsInVuaXF1ZV9uYW1lIjoiYWxpLTAxIiwicm9sZXMiOiJVc2VyIiwiZXhwIjoxNzU4MjI5MTIwLCJpc3MiOiJMb2NhbEhvc3QiLCJhdWQiOiJMb2NhbEhvc3QifQ.lKRRDfjGmEnLG-cKxCc4lUUIguBFghE57wS-bYwWp7E


###
POST {{Löwen.Api_HostAddress}}/add-review-for-product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjhmMmVmZDEwLTJkMWMtNDFlZS05YzRkLTJmN2Y1NDMxY2IxOCIsImp0aSI6ImZjOThlNjRkLTU4ZDctNGI2Yy1iZmZlLWU5NTdhNTllNzM1MyIsImVtYWlsIjoiYWUxMzc4MDMyQGdtYWlsMS5jb20iLCJ1bmlxdWVfbmFtZSI6ImFsaS0wMSIsInJvbGVzIjoiVXNlciIsImV4cCI6MTc1ODQwNTAzNiwiaXNzIjoiTG9jYWxIb3N0IiwiYXVkIjoiTG9jYWxIb3N0In0.WKPNQDy71WTlxknZLTZwRNpu8utbWvS6j1mQiL9gBWU
Content-Type: Application/json
{
  "productId": "f41ca530-ce12-4ca4-b468-80f5fc3da8db",
  "rating": "2",
  "review": "string"
}
###
PUT {{Löwen.Api_HostAddress}}/update-review-for-product
Content-Type: Application/json
{
  "productReviewId": "1146a90b-12d0-4021-83da-937eba6b59be",
  "rating": "3",
  "review": "Good"
}

###
DELETE {{Löwen.Api_HostAddress}}/remove-review-from-product/1146a90b-12d0-4021-83da-937eba6b59be